[profile.default]
src = 'contracts'
out = 'out'
libs = ['lib']
test = 'contracts/test'
cache_path = 'foundry-cache'
optimizer = true
optimizer_runs = 200
auto_detect_solc = true
gas_limit = 9223372036854775807

[profile.default.optimizer_details]
constantOptimizer = true
yul = false

[rpc_endpoints]
hyperspace = "${HYPERSPACE_RPC_URL}"
localnet = "${LOCALNET_RPC_URL}"

# See more config options https://github.com/foundry-rs/foundry/tree/master/config